spring:
  security:
    user:
      name: user
      password: password
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/online-shopping?allowPublicKeyRetrieval=true&useSSL=false

    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  redis:
    host: localhost
    port: 6379
  mvc:
    async:
      request-timeout: -1  # SSE 타임아웃 무한 설정
jwt:
  expiration: 100 #30?
  refresh-expiration: 86400 #100? #86400
  secretKey: mysecret
